/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Homework;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.geometry.Insets;
import javafx.scene.control.ComboBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.scene.text.Text;
import javafx.scene.control.TextField;



public class App extends Application{
    Stage window;
    Scene scene;
    Button button;
    ComboBox<String> comboBox;
    public static void main(String[] args){
        launch(args);

    }

    @Override
    public void start(Stage primaryStage) throws Exception {

       window = primaryStage;
       window.setTitle("Combobox Test");
       button = new Button("Submit");

       Text nameLabel = new Text("Course Name");
       TextField nameText = new TextField();
       Text nameLabel1 = new Text("CRN");
       TextField nameText1 = new TextField();
       Text nameLabel2 = new Text("Number of Credits");
       TextField nameText2 = new TextField();
       Text totallabel = new Text();
       comboBox = new ComboBox<>();
       comboBox.getItems().addAll(
               "Computer Science" ,
                       "Chemistry" ,
                       "Physics" ,
                       "Mathematics" ,
                       "Botany" ,
                       "Zoology"
       );

       comboBox.setPromptText("Select a Department");


       VBox layout = new VBox(10);
       layout.setPadding(new Insets(20,20,20,20));
       layout.getChildren().addAll(comboBox, nameLabel, nameText, nameLabel1, nameText1, nameLabel2, nameText2, button, totallabel);


       scene = new Scene(layout, 600,  400 );
       window.setScene(scene);
       window.show();
       String total = (comboBox.getValue() + ", " + nameText.getText() + ", " + nameText1.getText() + ", " + nameText2.getText());
       button.setOnAction(e -> System.out.println(comboBox.getValue() + ", " + nameText.getText() + ", " + nameText1.getText() + ", " + nameText2.getText()));
       //button.setOnAction(e -> totallabel( comboBox.getValue() + ", " + nameText.getText() + ", " + nameText1.getText() + ", " + nameText2.getText()));

       //if(comboBox.getValue() == 'Chemistry');
    }




}